- hosts: dcs
  vars:
    domain_name: "lab.example.local"
    local_admin: ".\administrator"
    dc_password: "P@ssw0rd1!"
    recovery_password: "P@ssw0rd1!"
  tasks:
    - name: Set Admin Password
      win_user:
         name: administrator
         password: '{{ dc_password }}'
         state: present
    - name: Reboot server to apply changes
      win_reboot:
    - name: Installing AD
      win_feature: >
        name=AD-Domain-Services
        include_management_tools=yes
        include_sub_features=yes
        state=present
      register: result
    - name: Create Domain
      win_domain: >
        dns_domain_name='{{ domain_name }}'
        safe_mode_password='{{ recovery_password }}'
      register: ad
    - name: Reboot server to apply changes
      win_reboot:
      when: ad.changed
    - name: Set internal DNS to localhost
      win_dns_client:
        adapter_names: '*'
        ipv4_addresses:
          - '127.0.0.1'
